### ISSUE TITLE
using putout in a Typescript based node.js that compiles into ESM

### ISSUE THREAD

**Issue by esakal** [coderaiser/putout#145]
Hello @coderaiser! Your library is incredible and I appreciate the philosophy behind it. It appears to be a perfect solution for code alterations.

I'm wondering whether there is a possibility of importing it into a TypeScript-based node.js library and compiling it to ESM?

**Comment by coderaiser** [comment]
Hi, thank you!

As ESM bundle it can be used with help of [`@putout/bundle`](https://github.com/coderaiser/putout#-usage-with-deno).

About TypeScript, could you provide more details?

**Comment by coderaiser** [comment]
> create a library that includes a collection of putout transformers
package the library as an ESM for npm, with the transformers being included internally rather than as plugins
run certain transformers from within my node library when a user executes a CLI command

Here is example of such ESM library ([`@putout/minify`](https://github.com/putoutjs/minify/)) + CLI ([`minify`](https://github.com/coderaiser/minify)).

> You suggested using @putout/bundle, which requires a list of plugins. However, since I am bundling my own CLI library and want the transformers to be included internally, I cannot place them under .putout.

You don't need to put them under `.putout`. Do you want to use in Deno, browser, single-file build? Or just ESM?

> Additionally, I am not sure if I can provide a transform file as opposed to a complete plugin, which would result in a library bundling another library.

Just use [Simple plugin](https://github.com/coderaiser/putout/blob/master/packages/engine-loader/README.md#simple-plugin) according to examples from [`@putout/engine-runner`](https://github.com/coderaiser/putout/tree/master/packages/engine-runner#supported-plugin-types).

> As an example, my transformers will modify code like the example below and add additional states, but I could not locate any documentation on this behavior.

That's not problem what you want change in provided example?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝.

Feel free to reopen when you need.
