### ISSUE TITLE
[eslint-plugin-putout]: New lines are still applied on other rule autofix, even if all `add-newline` rules are deactivated.

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#152]
In like the rules in putout, but every time I let putout autofix a rule, all `add-newline` rules are applied as well. They are not listed in the simple linting and I even deactivated them in my config:

```json
{
	"env": {
		"browser": true,
		"es2021": true,
		"node": true
	},
	"extends": [
		"plugin:putout/safe"
	],
	"parserOptions": {
		"ecmaVersion": "latest",
		"sourceType": "module",
	},
	"globals": {
		"document": true,
		"window": true
	},
	"settings": {
		"node": {
			"resolvePaths": ["node_modules/@types"],
			"extensions": [".js", ".json", ".ts", ".d.ts"]
		},
		"import/resolver": {
			"node": {
				"resolvePaths": ["node_modules/@types"],
				"extensions": [".js", ".json", ".node", ".ts", ".d.ts", ".vert", ".frag", ".glsl"]
			}
		}
	},
	"plugins": ["putout"],
	"rules": {
		"putout/putout": [2, {
		 	"plugins": ["apply-shorthand-properties"],
		 	"rules": {
		 		"apply-shorthand-properties": ["on", {
		 			"ignore": []
		 		}],
		 		"split-variable-declarations": "off",
		 		"new/remove-useless": "off",
		 		"remove-unused-variables": "off",
				"remove-console": "off"
			}
		}],
		"putout/add-newline-after-function-call": 0,
		"putout/add-newline-before-function-call": 0,
		"putout/add-newline-before-return": 0,
		"putout/add-newlines-between-specifiers": 0,
		"putout/add-newlines-between-types-in-union": 0,
		"putout/nonblock-statement-body-newline": 0,
		"putout/nonblock-statement-body-position": 0,
		"putout/multiple-properties-destructuring": 0,
	}
}
```

**Comment by coderaiser** [comment]
Looks like you need to set [`printer`](https://github.com/coderaiser/putout/tree/master#printer) to `recast`

**Comment by ElPrudi** [comment]
Nope, still get new lines below `if` cases, variable declarations and before return statements. It's nice for long functions, but not for 2 lines of code.

**Comment by coderaiser** [comment]
Please provide code examples

**Comment by ElPrudi** [comment]
This
```ts
export default class Vector {
    x: number
    y: number

    static NewVector(x: number | string, y: number) {
        const v = new Vector()
        if (typeof x === 'string') x = +x
        v.x = x
        v.y = y
        return v
    }
}
```

Turns for me into this
```ts
const isString = (a): a is string => typeof 'string'

export default class Vector {
    x: number
    y: number
    static NewVector(x: number | string, y: number) {
        const v = new Vector()
        if (isString(x)) x = +x

        v.x = x
        v.y = y
        return v
    }
}
```

While now I see that `recast` removed the new lines around the declarations and return, it doesn't remove it underneath the inlined if case.

**Comment by coderaiser** [comment]
OK, I see, look all things related to [`recast`](https://github.com/benjamn/recast) you can put in it's repo and hope that it will be fixed one day 😅...

About formatting transformed code this is much bigger problem, that can look like. The thing is it always change it's appearance because `AST` is very abstract, it has no information about newlines, indentations etc. This made for performance reasons, would be to slow to use Concrete Syntax Tree. Anyways guys make such thing works in Rust (https://rome.tools/).

Each formatter takes it's own way for formatting codebase from `AST`:
- `recast` - tries to preserve all tokens during parsing, and then tries to guess how it was before parsing, in 70% cases it works like a charm. For other cases I wrote [`eslint-plugin-putout`](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout#readme) which fixes all broken cases of `recast`, and you can achieve much more if use it (you can also override any kind of **ESLint** options).
- `@putout/printer` - not try  to guess, it just format code in a best possible way, it also used to [minify](https://github.com/coderaiser/minify) code, and has a [couple options](https://github.com/putoutjs/printer#overrides).
- `@babel/generator` - just prints working code, it doesn't look like something we have in github repositories or in our IDE's;

You can also use `prettier` afterwards, if none of this solutions doesn't feats you needs. Code formatting is always a compromise 🤷‍♂️.

**Comment by ElPrudi** [comment]
Yes, but is there any way to disable formatting at all? I just want to use the `prettier` code standard, but I don't want to lose access to the output rules.

**Comment by coderaiser** [comment]
There is [phases of transforming AST](https://github.com/coderaiser/putout/tree/master#-architecture):
![image](https://github.com/coderaiser/putout/assets/1573141/d8c763b8-46bb-4e97-9e34-741d9e325cc1)

You can't just skip `print` phase, but you can post process your sources in a way you like.

**Comment by ElPrudi** [comment]
Ok, but would it be possible to include the [API](https://prettier-doc.netlify.app/docs/en/api.html#:~:text=API%20If%20you%20want%20to%20run%20Prettier%20programmatically%2C,are%20formatting%20%28see%20the%20list%20of%20available%20parsers%29.) of `prettier` to format?

**Comment by coderaiser** [comment]
`prettier` doesn't takes `AST`, it works only with `string`, same with **ESLint**.

**Comment by ElPrudi** [comment]
God damn it. I guess I'll just have to live with it. Well, thanks anyway.
