### ISSUE TITLE
[types/convert-typeof-to-is-type]: autofixes to itself, if the function is the only function inside the file.

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#154]
I like the idea of this rule, but there is an edge case it doesn't look for. For clarity, I moved this function to it's own file:

```ts
export default function isString(value: unknown): value is string {
    return typeof value === 'string'
}
```

The funny thing is, `eslint-plugin-putout` see this as an error:

```
  2:12  error  Use function to check type instead of 'typeof' (types/convert-typeof-to-is-type)  putout/putout
```

And even funnier is, that it replaces the function body with itself:

```ts
export default function isString(value: unknown): value is string {
    return isString(value)
}
```

**Comment by coderaiser** [comment]
Thanks! Just fixed 🎉 , is it works for you?

**Comment by ElPrudi** [comment]
Does not work if you name your function differently. Instead of `isFn` I use `isFunction` and for `isBool` I use `isBoolean`. You need to find a way to specify this independently of the function name.

**Comment by coderaiser** [comment]
I don't think we should move far away from [current list functions](https://github.com/coderaiser/putout/blob/master/packages/plugin-types/README.md#declare), stick to it, and think good before apply big changes.

`isBool` is fine since there is [`__bool`](https://github.com/coderaiser/putout/tree/master/packages/compare#__bool), so this things are consistent, and `isFn` is short enough to understand what it is. There is also [`__args`](https://github.com/coderaiser/putout/tree/master/packages/compare#__args-__args__a) shorthand.

The main idea is: that's OK to use short names for functions used often. For example `Rust` simplifies syntax constructions, so this is the same code:

```rust
fn foo() -> i32 {
    return 3;
}
```

```rust
fn foo() -> i32 {
    3
}
```

It can look inconvenient on a first glance, but on the long run it is very comfortable.

**Comment by ElPrudi** [comment]
From that perspective, I understand. I would add a small hint that other function names are not recognized. I had assumed that it would be possible with PutoutScript to configure any aliases, for example to fix `isFn` with the alias `isFunction`. You have to decide. But from my point of view it would be completely fine.
