### ISSUE TITLE
[promises/remove-useless-async]: rule doesn't check for nested Promises on `return`

### ISSUE THREAD

**Issue by ElPrudi** [coderaiser/putout#155]
It seems that this rule does not do what is intended. Async functions always return as a promise, but this rule does not check if the return value of the promise is a promise that also awaits on return. This means that functions like this are considered errors:

```ts
async function stuff(): Promise<string> {
   return 'stuff'
}

async function doStuff(): Promise<string> {
    return stuff()
}

console.log(await doStuff()) // 'stuff'
```

Other eslint plugins like typescript-eslint do not see this as a problem.

**Comment by coderaiser** [comment]
The problem is there is no need in promise at all for such function:

```js
async function stuff(): Promise<string> {
   return 'stuff'
}
```

You can write it as:

```js
function stuff(): string {
   return 'stuff'
}
```

And still call as `await stuff()`.

About this case:

```js
async function doStuff(): Promise<string> {
    return stuff()
}
```

Better to always use `await` like this:

```js
async function doStuff(): Promise<string> {
    return await stuff()
}
```

It is not only more readable and gives more information about function you going to call (especially when you don't use TypeScript), but it is also [faster and produces callstackes](
https://stackoverflow.com/a/70979225/4536327).

**Comment by coderaiser** [comment]
Just published a new plugin [`typescript/remove-useless-promise`](https://github.com/coderaiser/putout/tree/master/packages/plugin-typescript#remove-useless-promise) 🎉.

You can take at a look at it at 🐊[**Putout Editor**](https://putout.cloudcmd.io/#/gist/5fd13c0510571b45884dfddbc8b83bb4/5ca97c4021b197822ef73418796513fe6d891239);
