### ISSUE TITLE
It it possible to use Putout as Eslint backend?

### ISSUE THREAD

**Issue by artalar** [coderaiser/putout#210]
Hi! I'm very inspired by Putout, the scripting language looks super handy for me.

I have developed a library https://reatom.dev that has a list of rules and best practices that could be automated for a user-developer by eslint plugin. It is important to provide a plugin for eslint as it is a very popular lint tool which has the best IDE integrations. But I as a library developer don't want to write eslint mathes, as it has quite complex API, which is hard to manage.

And I have an idea, is it possible to write the lint tool logic with putout, but produce the output to eslint rule?

For example, here is the case I want to solve: https://github.com/artalar/reatom/issues/523

**Comment by coderaiser** [comment]
Hi, nice library! I can suggest you two options:

- [`@putout/eslint`](https://github.com/coderaiser/putout/tree/master/packages/eslint#createpluginoptions) - simplifies ESLint API, and make it fill almost like 🐊**Putout** Plugin;
- [`eslint-plugin-putout`](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout#rules) - has `putout` rule, so you can write 🐊**Putout** plugins, and use it IDE of your choice, since ESLint will run the code;
