### ISSUE TITLE
putout/destructuring-as-function-argument - prefer multiple lines

### ISSUE THREAD

**Issue by oprogramador** [coderaiser/putout#52]
How can I obtain a behavior reverse to https://github.com/coderaiser/putout/tree/e0438b8526d7df5bf31cc95d7c43590e9757d8d6/packages/eslint-plugin-putout/lib/destructuring-as-function-argument - enforcing each property in a separate line?

**Comment by coderaiser** [comment]
Why do you need it? Do you have a lot parameters you are going to destructure like:

```js
function parse({name, password, mail, address}) {
    return `${name}-${password}-${mail}-${address}`;
}
```

Into:

```js
function parse({
    name,
    password,
    mail,
    address,
}) {
    return `${name}-${password}-${mail}-${address}`;
}
```

I think it looks unnatural, and this way is more readable:

```js
function parse(user) {
    const {
        name,
        password,
        mail,
        address,
    }  = user;
    
    return `${name}-${password}-${mail}-${address}`;
}
```

And if you going to use `typescript in future`, it will look this way:

```ts
interface User {
    name: 'string',
    password: 'string',
    mail: 'string',
    address: 'string',
}

function parse(user: User) {
    const {
        name,
        password,
        mail,
        address,
    }  = user;
    
    return `${name}-${password}-${mail}-${address}`;
}
```

So you will definitely need the interface `User` and the shorter and simpler header of your function, the faster to understand what id does, because of  [7 +-2](https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two) and [incapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)) of object properties using higher order entities.

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝

**Comment by oprogramador** [comment]
When there are between 3 and 8 named params, I'd like to have them in separate lines without a need to group them into a single param because these params are mostly very different and they don't belong to a single entity e.g.:
- database model
- FTP client
- API service to fetch something
- logger
- query
- callback called for each fetched item
- number of items processed in parallel
- timeout
- initial index
- limit of items to process
- delay between a failure and retrying

**Comment by coderaiser** [comment]
Could you please provide code examples?

**Comment by oprogramador** [comment]
```js
function processItems({
  model,
  ftpClient,
  currenciesAPI,
  logger,
  query,
  onFetchedItem,
  maxItemsInParallel,
  timeoutInMillis,
  initialIndex,
  limit,
  delayAfterFailure,
}) {
```

**Comment by coderaiser** [comment]
Maybe the code you are using can be refactored to use a couple functions? Could you please give more detailed example?
I have a couple places in `putout` with a long list of parameters (not proud of it, and hope to shorten when I will know how):
- [putout/lib/cli/process-file](https://github.com/coderaiser/putout/blob/v16.2.0/packages/putout/lib/cli/process-file.js#L20)
- [engine-processor/lib/processor](https://github.com/coderaiser/putout/blob/v16.2.0/packages/engine-processor/lib/processor.js#L26)

Anyways it should not be a rule of thumb to use such a long list, because it breaks the rule of [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well):

> Do one thing and do it well

And this principles helps to write high quality and easily maintainable programs.

**Comment by oprogramador** [comment]
Thanks for the answer.

Maybe I'll follow up next time when I need to use putout.
