### ISSUE TITLE
Recast seems to be unmaintained 

### ISSUE THREAD

**Issue by FredericEspiau** [coderaiser/putout#89]
Hey and thanks for the hard work !

Do you plan on getting rid of `recast` ? It can't parse most recent code bases and it seems to be pretty much abandoned by its maintainer

For example, it can't handle `StaticBlock`, even though it's supported by TS for a few months now

Babel parser is still updated regularly for example: https://github.com/babel/babel/blob/54c539ecc12a70706e642ef9354b2ece6360444a/packages/babel-parser/src/types.js (there is a definition for `StaticBlock`)

**Comment by coderaiser** [comment]
Hi @FredericEspiau thank you, `recast` doing hard work changing as little code as possible,
And do it much better than `Babel` which is greatest parser of all times :).

But yes, it's very purely maintained, that's why it is forked to [`@putout/recast`](https://github.com/coderaiser/recast) and when I trap on bugs, I [fix it myself](https://github.com/coderaiser/recast#fork-contains-unmerged-fixes).

About `StaticBlock` if you need support for it, you can send `PR` to my fork, and I'll merge it :).

**Comment by FredericEspiau** [comment]
Alright thanks I'll see what I can do, it doesn't look too hard :)

**Comment by coderaiser** [comment]
I see no problem with 🐊`Putout` while using [`Static Block`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_static_initialization_blocks).
So I close this issue.

Could you please show me how do you use it? And why do you need it in `recast`?
