### ISSUE TITLE
Extraneous dependencies with Yarn v3

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#93]
When I try to use Putout with Yarn v3, I get the following error:

```text
🐊 @putout/formatter-progress-bar: simport tried to access @putout/formatter-progress-bar, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @putout/formatter-progress-bar (via "@putout/formatter-progress-bar/package.json")
Required by: simport@npm:1.2.0 (via /Users/evgeny/Downloads/putout-yarn3/.yarn/cache/simport-npm-1.2.0-c4f61c3792-85716020b4.zip/node_modules/simport/simport.js)
```

Steps to reproduce:

1. `git clone git@github.com:EvgenyOrekhov/putout-yarn3.git`
2. `cd putout-yarn3`
3. `yarn`
4. `yarn putout .`

Looks similar to https://github.com/coderaiser/putout/issues/92.

**Comment by coderaiser** [comment]
It looks like an issue of `yarn`, [`simport`](https://github.com/coderaiser/simport) simplifies dynamic loading of `ESM` and fixes issues related to `windows` it can `import` any module and do not have to have it in `package.json`. Same with dynamic nature of loading plugins in 🐊`Putout`. `ESLint` works in similar way but with `CommonJS`.

**Comment by coderaiser** [comment]
OK, so there is a thing called [`PnP loose mode`](https://yarnpkg.com/features/pnp#pnp-loose-mode) to get this working, `.yarnrc` should be updated to:

```diff
yarnPath: ".yarn/releases/yarn-berry.cjs"
+pnpMode: "loose"
```

But after that a new error appear:

```
(node:79903) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:79903) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(node:79903) [MODULE_NOT_FOUND] Error: simport tried to access @putout/formatter-progress-bar, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

🐊 @putout/formatter-progress-bar: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: #ansi-styles (via "#ansi-styles/package.json")
Required by: chalk@npm:5.0.0 (via /Users/coderaiser/putout-yarn3/.yarn/cache/chalk-npm-5.0.0-7be183234e-6eba7c518b.zip/node_modules/chalk/source/index.js)
```

The thing is `chalk` uses [imports map](https://github.com/chalk/chalk/blob/v5.0.0/package.json#L10-L16) and `#ansi-styles` doesn't even have [`package.json`](https://github.com/chalk/chalk/tree/v5.0.0/source/vendor/ansi-styles).

Yarn Plug'n'play is nice feature, but it's not ready for using in real world yet (especially `ESM` which just trying to get on his feet in dual packages mode working closely to `CommonJS`).

So I'm glad to help, and will try to do steps required from my side, but there is a lot things that needs to be done from other maintainers of popular packages and node.js itself, because `node loaders` is still experimental and subject to change.

**Comment by coderaiser** [comment]
I understood, it's possible to avoid a lot of warnings if [`createRequire`](https://nodejs.org/api/module.html#module_module_createrequire_filename) hack [will be used](https://yarnpkg.com/advanced/rulebook#modules-shouldnt-hardcode-node_modules-paths-to-access-other-modules) by [`@putout/engine-loader](https://github.com/coderaiser/putout/master/tree/packages/engine-loader).

This is the only way `.pnp.cjs` will work in correct way, because it puts everything from `node_modules` to itself:

```sh
-rwxr-xr-x    1 coderaiser  staff   1.2M Dec 15 18:59 .pnp.cjs*
```

About formatters, `putout v21` uses `CommonJS` versions of formatters.

**Comment by coderaiser** [comment]
Landed ability to benefit from `Yarn PnP` in `@putout/engine-loader v4.10.0` 🎉 !
It will work without warnings :)! And no `loose` mode needed. This is when 🐊`Putout` used as a plugin for `ESLint`.

If 🐊`Putout` used as standalone, `pnpMode` should be set to `loose`, and version of 🐊`Putout` should be decreased to `v22`, because `chalk v5` isn't supported by `yarn PnP` https://github.com/yarnpkg/berry/issues/3843.

Or `CommonJS` version of formatter should be installed, or `json`, `json-lines` or `eslint` formatter used.

I think we can come back to this in the future, when `yarn PnP` became more mature :).

**Comment by coderaiser** [comment]
Landed support of yarn PnP in 🐊[`Putout v22.8.0`](https://github.com/coderaiser/putout/releases/tag/v22.8.0) 🎉 !
Is it works for you?

**Comment by coderaiser** [comment]
I found out a little more details from [yarn documentation](https://yarnpkg.com/advanced/rulebook/#modules-shouldnt-hardcode-node_modules-paths-to-access-other-modules):

![image](https://user-images.githubusercontent.com/1573141/146430272-d230bd51-591c-477f-9a7c-602ff0b8e816.png)

I described details in [docs](https://github.com/coderaiser/putout#integration-with-yarn-pnp). Could you please try to run `eslint` with:

`PUTOUT_YARN_PNP=eslint-config-hardcore yarn lint .`

@spa5k @EvgenyOrekhov is this way of running works for you?

**Comment by coderaiser** [comment]
```sh
coderaiser@localcmd:~/putout-yarn3$ yarn lint
./pages/1.tsx
1:22  Error: Replace `'xx'` with `"xx"`  prettier/prettier
1:22  Error: Strings must use doublequote.  quotes
3:1  Error: exported declaration 'setSession' not used within other modules  import/no-unused-modules
3:1  Error: Prefer default export.  import/prefer-default-export
3:14  Error: Expected a function declaration.  func-style
4:1  Error: Replace `····` with `··`  prettier/prettier
5:1  Error: Replace `····` with `··`  prettier/prettier
5:5  Error: Shorthand properties should be used (apply-shorthand-properties)  putout/putout 🔥🔥🔥🔥🔥🔥🔥
7:1  Error: Delete `⏎`  prettier/prettier

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
coderaiser@localcmd:~/putout-yarn3$ ls -lha node_modules/ 🔥🔥🔥🔥🔥🔥🔥
total 0 
drwxr-xr-x   3 coderaiser  staff    96B Dec 16 20:19 ./
drwxr-xr-x  21 coderaiser  staff   672B Dec 17 16:20 ../
drwxr-xr-x   3 coderaiser  staff    96B Dec 16 20:19 .cache/
coderaiser@localcmd:~/putout-yarn3$ vi .m
coderaiser@localcmd:~/putout-yarn3$ ls -lha
total 3480
drwxr-xr-x   21 coderaiser  staff   672B Dec 17 16:20 ./
drwxr-xr-x+ 210 coderaiser  staff   6.6K Dec 17 16:19 ../
-rw-r--r--    1 coderaiser  staff    54B Dec 17 15:44 .eslintrc.json
drwxr-xr-x   12 coderaiser  staff   384B Dec 17 15:32 .git/
-rw-r--r--    1 coderaiser  staff   495B Dec 16 15:55 .gitignore
drwxr-xr-x    3 coderaiser  staff    96B Dec 16 15:59 .next/
-rwxr-xr-x    1 coderaiser  staff   1.3M Dec 17 16:20 .pnp.cjs* 🔥🔥🔥🔥🔥🔥🔥
-rw-r--r--    1 coderaiser  staff   7.8K Dec 16 16:09 .pnp.loader.mjs 
-rw-r--r--    1 coderaiser  staff    43B Dec 16 16:09 .putout.json
drwxr-xr-x    6 coderaiser  staff   192B Dec 17 15:11 .yarn/
-rw-r--r--    1 coderaiser  staff    58B Dec 16 19:42 .yarnrc.yml
-rw-r--r--    1 coderaiser  staff   1.5K Dec 16 15:55 README.md
-rw-r--r--    1 coderaiser  staff   201B Dec 16 15:55 next-env.d.ts
-rw-r--r--    1 coderaiser  staff    87B Dec 16 15:55 next.config.js
drwxr-xr-x    3 coderaiser  staff    96B Dec 16 20:19 node_modules/
-rw-r--r--    1 coderaiser  staff   668B Dec 17 15:59 package.json
drwxr-xr-x    6 coderaiser  staff   192B Dec 17 15:59 pages/
drwxr-xr-x    4 coderaiser  staff   128B Dec 16 15:55 public/
drwxr-xr-x    4 coderaiser  staff   128B Dec 16 15:55 styles/
-rw-r--r--    1 coderaiser  staff   509B Dec 16 15:55 tsconfig.json
-rw-r--r--    1 coderaiser  staff   406K Dec 17 16:20 yarn.lock
coderaiser@localcmd:~/putout-yarn3$ cat package.json
{
  "name": "next-putout",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "PUTOUT_YARN_PNP=eslint-config-hardcore next lint", 🔥🔥🔥🔥🔥🔥🔥
    "putout": "putout"
  },
  "dependencies": {
    "eslint-config-hardcore": "^23.6.1",
    "eslint-plugin-prettier": "^4.0.0",
    "next": "12.0.7",
    "prettier": "^2.5.1",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@types/node": "16.11.13",
    "@types/react": "17.0.37",
    "eslint": "8.4.1",
    "eslint-config-next": "12.0.7",
    "putout": "^22.8.0",
    "typescript": "4.5.4"
  },
  "packageManager": "yarn@3.1.1"
}
coderaiser@localcmd:~/putout-yarn3$ cat .yarnrc.yml
yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: "pnp" 🔥🔥🔥🔥🔥🔥🔥
coderaiser@localcmd:~/putout-yarn3$ cat .eslintrc.json
{
  "extends": ["next/core-web-vitals", "hardcore"] 🔥🔥🔥🔥🔥🔥🔥
}

**Comment by EvgenyOrekhov** [comment]
@coderaiser I tried following your example (I added `PUTOUT_YARN_PNP=eslint-config-hardcore` and `nodeLinker: "pnp"`), still getting the following error:

```text
❯ yarn lint       
Error: Error while loading rule 'putout/putout': @putout/engine-loader tried to access putout, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: putout
Required by: @putout/engine-loader@npm:4.12.0 (via /Users/evgeny/Downloads/next-ts/.yarn/cache/@putout-engine-loader-npm-4.12.0-5f341bbac6-8b4eda1515.zip/node_modules/@putout/engine-loader/lib/)

Require stack:
- /Users/evgeny/Downloads/next-ts/.yarn/cache/@putout-engine-loader-npm-4.12.0-5f341bbac6-8b4eda1515.zip/node_modules/@putout/engine-loader/lib/load.js
- /Users/evgeny/Downloads/next-ts/.yarn/cache/@putout-engine-loader-npm-4.12.0-5f341bbac6-8b4eda1515.zip/node_modules/@putout/engine-loader/lib/index.js
- /Users/evgeny/Downloads/next-ts/.yarn/cache/putout-npm-22.8.2-a2610271e6-0eb95d2c51.zip/node_modules/putout/lib/putout.js
- /Users/evgeny/Downloads/next-ts/.yarn/__virtual__/eslint-plugin-putout-virtual-bf92a01363/0/cache/eslint-plugin-putout-npm-12.7.1-027a8abd29-50896c563d.zip/node_modules/eslint-plugin-putout/lib/array-element-newline/index.js
- /Users/evgeny/Downloads/next-ts/.yarn/__virtual__/eslint-plugin-putout-virtual-bf92a01363/0/cache/eslint-plugin-putout-npm-12.7.1-027a8abd29-50896c563d.zip/node_modules/eslint-plugin-putout/lib/index.js
- /Users/evgeny/Downloads/next-ts/.yarn/cache/@eslint-eslintrc-npm-1.0.5-bd5ac53f2a-b35b50d7b6.zip/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
Occurred while linting /Users/evgeny/Downloads/next-ts/pages/_app.tsx
```

I created a reproducible case here: https://github.com/EvgenyOrekhov/putout-yarn3/tree/PUTOUT_YARN_PNP

Steps to reproduce:

```sh
git clone git@github.com:EvgenyOrekhov/putout-yarn3.git
cd putout-yarn3
git checkout PUTOUT_YARN_PNP
yarn lint
```

**Comment by EvgenyOrekhov** [comment]
@coderaiser Hmm I have putout declared in eslint-config-hardcore's dependencies:

https://github.com/EvgenyOrekhov/eslint-config-hardcore/blob/ab59bf254d228f561f2b7a77d9cd470b2cfb2e2f/package.json#L75

I expected that it should work without using `yarn add putout`.

**Comment by coderaiser** [comment]
Looks that `Yarn PnP` thinks that 🐊`Putout` should be in top level 🤷‍♂️

**Comment by spa5k** [comment]
Try adding this - https://www.npmjs.com/package/@rushstack/eslint-patch

It is useful in cases of yarn and monorepos.

**Comment by mrienstra** [comment]
> I think we can come back to this in the future, when `yarn PnP` became more mature :).

The future is peeking up over the horizon, [yarnpkg/berry#3843](https://github.com/yarnpkg/berry/issues/3843) was fixed yesterday. The fix is available in `4.0.0-rc.22`. Run [`yarn set version canary`](https://yarnpkg.com/cli/set/version) if you want to try it. v4 release is still a little ways off ("may take a couple more months"), but:
>[...] what's in master is stable, and I'd recommend you to try it. The only notable difference with stable is that we reserve the right to land a couple more breaking changes in future RCs, but in terms of stability it's almost always better to use RCs than stable.

... according to https://github.com/yarnpkg/berry/discussions/4895

See https://github.com/yarnpkg/berry/issues/3591 for v4 breaking changes. I've seen two mentions of people stumbling over `enableGlobalCache` default changing from `false` to `true`. ([Google search: site:yarnpkg.com "enableGlobalCache"](https://www.google.com/search?q=site%3Ayarnpkg.com+%22enableGlobalCache%22))

**Comment by coderaiser** [comment]
@mrienstra [Yarn PnP is supported for a long time](https://github.com/coderaiser/putout#-integration-with-yarn-pnp). Is it works for you?

**Comment by mrienstra** [comment]
@coderaiser, just spreading the news about https://github.com/yarnpkg/berry/issues/3843. [This comment](https://github.com/coderaiser/putout/issues/93#issuecomment-995087957):

>If 🐊Putout used as standalone, pnpMode should be set to loose, and version of 🐊Putout should be decreased to v22, because chalk v5 isn't supported by yarn PnP https://github.com/yarnpkg/berry/issues/3843.
>
>Or CommonJS version of formatter should be installed, or json, json-lines or eslint formatter used.
>
>I think we can come back to this in the future, when yarn PnP became more mature :).

.. states that standalone usage of 🐊Putout is limited to <= v22 due to https://github.com/yarnpkg/berry/issues/3843, wanted to share that this will likely no longer be the case when Yarn v4 is used.

**Comment by coderaiser** [comment]
> .. states that standalone usage of 🐊Putout is limited to <= v22

That’s no longer the case, 🐊Putout uses lower version of chalk, and yarn PnP is supported.
